### PR TITLE
Bumped PHP to 7.1 and updated PHPUnit to ^6.2.2

### PR DESCRIPTION
**Pull request by webimpress**
- dropped PHP 5.6 and 7.0 support
- updated travis configuration to run on PHP 7.2 (nightly)
- bumped requirements to PHP 7.1
- updated PHPUnit to 6.2.2
- `::class` notation in tests
- removed PHP5.6/7.0 residues

### CODE REVIEW

**Comment by Ocramius** [comment]
We can bump everything to 7.1, as other zf components are also finally
doing it

**Comment by webimpress** [comment]
@Ocramius 
> We can bump everything to 7.1, as other zf components are also finally doing it

Do you want to do it in this PR?

**Comment by Ocramius** [comment]
Yep

**Comment by webimpress** [comment]
@Ocramius all done

**Comment by Ocramius** [comment]
:ship:

Thanks @webimpress!

**Pull request merged**
