### PR TITLE
Add 'returntype' case to MethodGenerator::fromArray()

### PR DESCRIPTION
**Pull request by djmattyg007**

### CODE REVIEW

**Comment by weierophinney** [comment]
Can you add a test for this, please?

**Comment by djmattyg007** [comment]
Sure, I'll get to it tonight hopefully.

**Comment by djmattyg007** [comment]
All done.

**Comment by Ocramius** [comment]
Merged into `develop` at zendframework/zend-code@da7ef15d562ee3b7c3388c6f2cd08fe1f6fb7c49

Thanks @djmattyg007, and sorry for the delay!

**Pull request closed without merging**
