### PR TITLE
Enable Travis CI slack notifications

### PR DESCRIPTION
**Pull request by xtreamwayz**

### CODE REVIEW

**Comment by webimpress** [comment]
@xtreamwayz can you update this PR and remove IRC from travis? I see that IRC channel has been closed. Maybe then we can have it merged before next release

/cc @Ocramius

**Comment by xtreamwayz** [comment]
I'd like to do that once I know what @weierophinney is up to with his side project. As I understood correctly, then we don't need the slack token anymore and all merged tokens might need to be removed.

**Comment by weierophinney** [comment]
I'm hoping I can finish up this week; I'll keep you updated. Once I'm done,
we can definitely remove all notifications from the Travis config.

**Comment by xtreamwayz** [comment]
Superseded and automated by zendframework/zfbot!

I think I closed all related open PR's now.

**Pull request closed without merging**
