### PR TITLE
Import PHP internal functions

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by Ocramius** [comment]
@webimpress just a note: while `zend-servicemanager` is a performance-sensitive component, this one is not. Not sure if worth pursuing performance improvements here.

**Comment by webimpress** [comment]
@Ocramius thanks for that note. I thought you'd like to have it as a standard now, this is why I wrote the sniff. But we can have disabled it by default and just enable in _performance-sensitive components_

**Comment by Ocramius** [comment]
Merging it for now - it's still a decent improvement, and you put quite some effort in it :-)

**Comment by Ocramius** [comment]
Merged manually to `develop` via zendframework/zend-code@1dd02307a99f463f637deab1dd11a8f6e5fa004e. Thanks @webimpress!

**Comment by mikeSimonson** [comment]
@webimpress What is the tool that you used to generate this ?

**Comment by webimpress** [comment]
@mikeSimonson 
It is going to be a part of new zend-coding-standard. You can find the sniff in my PR:
https://github.com/zendframework/zend-coding-standard/pull/1/files#diff-02ee2a3197d92d5f724d0d7dffc13ac0

I still need to work on it, but when you check out the branch you can use that sniff separately.
I have plan to work on sniffs this week, and hopefully finish it till end of this year ! :)

**Pull request closed without merging**
