### PR TITLE
Drop hhvm build, added PHP 7.2 (nightly) build

### PR DESCRIPTION
**Pull request by webimpress**

### CODE REVIEW

**Comment by Ocramius** [comment]
Please change this to target develop

**Comment by webimpress** [comment]
@Ocramius changed now

**Comment by webimpress** [comment]
@Ocramius tests are failing on PHP 7.2. It seems we need finally update PHPUnit... Version 4.8 is no longer supported.

**Comment by Ocramius** [comment]
About damn time 😁

**Comment by webimpress** [comment]
I've cherry-picked this commit into PR #114.

**Pull request closed without merging**
