### PR TITLE
Trying to fix a platform issue with windows line ending

### LINKED ISSUE #39: Issue with new lines on windows
I'm using PHP on windows but have set IDE intentionally to make unix new lines ``\n``, not windows ones ``\r\n``.
When running ``FileGenerator::fromReflectedFileName()`` on such file, I got exception

```
Undefined offset: 1

D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:98
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\MethodGenerator.php:77
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\ClassGenerator.php:146
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\FileGenerator.php:96
D:\www\home\tmilos\model\vendor\zendframework\zend-code\src\Generator\FileGenerator.php:77
```

Tested on zendframework/zend-code v3.0.1

Debuging shows the source of the problem is with inconsistent line endings in the project:

1) During loading ``MethodReflection::extractMethodContents()`` implodes lines with ``\n``

2) While ``MethodGenerator::clearBodyIndention()`` explodes what ``MethodReflection`` did before with ``PHP_EOL``

So, it seems this lib will work only if ``PHP_EOL === "\n"`` and guess that excludes php windows builds.

It would be nice you fix that and use consistent line endings.

### LINKED ISSUE #45: Line ending bug on windows
Hi,

I received a bug report on [doctrine/doctrineMigrationsBundle](https://github.com/doctrine/DoctrineMigrationsBundle/issues/154) for an elusive bug that only happen on windows. It looks like this code line is the cause of the issue. https://github.com/zendframework/zend-code/blob/master/src/Generator/MethodGenerator.php#L96

I guess that the assumption is that the first line will always be an empty one (aka only containing a new line). It works perfectly on linux but on windows the explode call might return the whole body of the function as one line. Explode will never find the windows line ending (\r\n) if the code was build on linux.

From that assumption, the issue could be fixed just by replacing the the PHP_EOL param with "\n" but I don't know what kind of side effect the trailling "\r"might cause.

Thanks for your time

### PR DESCRIPTION
**Pull request by mikeSimonson**
Uniformazing the line ending in the project to avoid issue
with windows.

Fix #45 and Fix #39

### CODE REVIEW

**Comment by krzysiekpiasecki** [comment]
IMHO we should always outputting with \PHP_EOL.

**Comment by mikeSimonson** [comment]
The problem is that you can only reliably split on "\n" and if you sometimes output code using PHP_EOL then you will leave some "\r" randomly in the output on windows. I don't know if it could cause issue though.

**Comment by mikeSimonson** [comment]
Ping @weierophinney

**Comment by Ocramius** [comment]
> IMHO we should always outputting with `\PHP_EOL`.

The fact that this generates different code on windows and on proper operating systems (:trollface:) is already a show-stopper for using `\PHP_EOL`.

I think the fix is legit, but we need to check if the tests need some changes too. @mikeSimonson did you check if these modified paths are covered by tests that expect `"\n"` or `\PHP_EOL`?

**Comment by krzysiekpiasecki** [comment]
> The fact that this generates different code on windows and on proper operating systems (:trollface:) is already a show-stopper for using \PHP_EOL.

This is the general idea. For example: Outputting to the files according to operation system sound reasonable. When collaborating with files we have 'converters' etc.  or maybe the better is using one proper operating system :)

In this case using PHP_EOL prevent us from bug observed on Windows machines during ```composer install```

```php
    $lines = explode(PHP_EOL, $body);
```

Nothing more is need it to fix this bug.

**Comment by Ocramius** [comment]
> Outputting to the files according to operation system sound reasonable.

No, ZF in general has a "no dependency on configuration/environment", nor "modification of environment" policy.

The components should behave in the same way regardless of the OS. Generated code is considered an output.

**Comment by mikeSimonson** [comment]
@Ocramius Do I need to change anything ?

**Comment by Ocramius** [comment]
@mikeSimonson I'd need you to just check whether any tests are still relying on PHP_EOL. They should all verify only `\n` line-endings.

**Comment by mikeSimonson** [comment]
@Ocramius I think its fixed. There is only one reference left to PHP_EOL in [this file](https://github.com/zendframework/zend-code/blob/master/test/Generator/TestAsset/TestClassWithManyProperties.php#L39). The test pass if it's uncommented and converted to \n. Should I add that too ?

The failure is only related to an update of phpcs. I am looking into the rule that need to be set to remove the failures.

**Comment by Ocramius** [comment]
@mikeSimonson thanks

**Comment by mikeSimonson** [comment]
@weierophinney Thanks

**Pull request merged**
