### PR TITLE
[BC Break] Remove annotations support for 4.0

### PR DESCRIPTION
**Pull request by lisachenko**
This PR removes annotations API for 4.0 as proposed by @Ocramius in https://github.com/zendframework/zend-code/issues/32
Also removed the `zendframework/zend-eventmanager` dependency.

- [x] Remove all annotation API from classes
- [x] Remove all annotation related classes and tests from the library
- [x] Remove `zendframework/zend-eventmanager` dependency
- [x] Rebase on `develop` branch
- [x] Regenerate `composer.lock` file
- [x] Document changes in the `CHANGELOG.md`
- [x] Investigate build failure in the test https://travis-ci.org/zendframework/zend-code/jobs/364674886

### CODE REVIEW

**Comment by lisachenko** [comment]
Added several tasks into the check list

**Comment by lisachenko** [comment]
BTW, should we define a 2.x from the develop branch and push it only with deprecation notices for annotation API?

**Comment by Ocramius** [comment]
Not really needed tbh, as the user-base for annotations in here is quite narrow (I know of this mostly because I never receive any bug reports about annotations ;-) )

**Comment by lisachenko** [comment]
Awaiting approval on this PR

**Comment by Ocramius** [comment]
@weierophinney if you are ok with this I'll start pushing for `4.x` overall.

**Comment by weierophinney** [comment]
@Ocramius Totally on board!

**Comment by Ocramius** [comment]
Alright, I suppose I need to revive some patches here over the next weekend :P

**Comment by lisachenko** [comment]
> Alright, I suppose I need to revive some patches here over the next weekend :P

Ok, let's proceed with strict types then and bump PHP version)

**Pull request merged**
