### PR TITLE
New coding standard

### PR DESCRIPTION
**Pull request by Koopzington**
Usage of the newly introduced zendframework/zend-coding-standard for CS checks.

### CODE REVIEW

**Comment by webimpress** [comment]
@Koopzington I think you should rebase it and change target to develop.
@Ocramius would you like to merge it for 3.2.0 release?

**Comment by Ocramius** [comment]
Yes, this should target develop: can also be merged then.

@Koopzington sorry for not noticing it upfront

**Comment by webimpress** [comment]
@Koopzington @Ocramius I've rebased this PR and created #120 with target to develop.

**Comment by Ocramius** [comment]
Handled in #120

**Pull request closed without merging**
